theme: jekyll-theme-cayman
title: Anchored Collar Mechanisms for 3D Navier Stokes
description: Preprint manuscript

markdown: kramdown

url: "https://kschatz.github.io"
baseurl: "/navier-stokes-3d-anchored-collar"

plugins:
  - jekyll-sitemap
