theme: jekyll-theme-cayman
title: Anchored Collar Mechanisms for 3D Navier Stokes
description: Preprint using a local scale-invariant anchored collar mechanism to prove global regularity for the 3D Navierâ€“Stokes equations.

markdown: kramdown

url: "https://kschatz.github.io"
baseurl: "/navier-stokes-3d-anchored-collar"

plugins:
  - jekyll-sitemap
